# Project-wide Gradle settings.
# Automatically convert third-party libraries to use AndroidX and enable library
# modularization
android.useAndroidX=true
android.enableJetifier=true

# Kotlin code style
kotlin.code.style=official

# Enable R8 full mode
android.enableR8.fullMode=true

# Parallel builds
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configureondemand=true